name: pangeo
channels:
  - conda-forge
dependencies:
  - python=3.6*
  - pip=20
  - cartopy
  - cftime
  - xarray
  - dask
  - distributed
  - dask-kubernetes
  - gcsfs
  - intake
  - intake-esm
  - intake-xarray
  - zarr
  - matplotlib
  - numpy
  - numcodecs
  - python-blosc
  - lz4
  - nomkl
  - nbserverproxy
  - nodejs=11 
  - jupyter
  - jupyterlab=0.35
  - jupyterlab_launcher
  - jupyter_client
  - ipywidgets
  - graphviz 
  - pip:
    - kubernetes
    - graphviz
